name: Var branch main
on:
  pull_request:
    branches:
      - main

jobs:
  check-branch:
    runs-on: ubuntu-latest
    steps:
      - name: Verify source branch
        if: github.head_ref != 'dev'
        run: |
          echo "Error: Don't merge to main!"
          exit 1